# -*- coding: utf-8 -*-
# """삼성증권PB대시보드_포트폴리오로직초안.ipynb

# Automatically generated by Colab.

#Original file is located at
#    https://colab.research.google.com/drive/17sR_lsDNpVcYRAGeHgUINtO69EctAAv5
# """

# !pip install yfinance -q

# Colab 한글 폰트 설치
# !apt-get -qq install fonts-nanum

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib as mpl

# 나눔고딕 폰트 경로
# font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"

# 폰트 등록
# fm.fontManager.addfont(font_path)
# font_name = fm.FontProperties(fname=font_path).get_name()

# Matplotlib 기본 폰트 설정
# plt.rcParams["font.family"] = font_name

# 마이너스 기호 깨짐 방지
# plt.rcParams["axes.unicode_minus"] = False

# print("현재 폰트:", font_name)

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import json
import warnings

warnings.filterwarnings("ignore")

TRADING_DAYS = 252

# =========================
# 사용자 입력 영역
# =========================

risk_free_rate = 0.035  # 무위험수익률 3.5%
initial_amount = 3_000_000_000  # 초기 투자금 30억 예시

# 세금/비용 단순 가정
tax_config = {
    "dividend_tax_rate": 0.154,       # 배당소득세 단순 가정
    "capital_gains_tax_rate": 0.22,   # 해외주식 양도세 단순 가정
    "trading_fee_rate": 0.001,        # 거래수수료 0.1% 단순 가정
    "fx_fee_rate": 0.002,             # 환전비용 0.2% 단순 가정
    "annual_turnover": 1.0            # 연간 포트폴리오 1회전 가정
}

# 포트폴리오 예시
# 주의: weights 합계는 반드시 1이어야 함
portfolios = {
    "현재 포트폴리오": {
        "tickers": ["SPY", "TLT", "GLD", "VNQ", "DBC"],
        "weights": [0.50, 0.20, 0.10, 0.10, 0.10],
        "asset_classes": {
            "SPY": "미국주식",
            "TLT": "장기채권",
            "GLD": "금",
            "VNQ": "리츠",
            "DBC": "원자재"
        }
    },
    "추천 A_안정형": {
        "tickers": ["SPY", "TLT", "IEF", "GLD", "VNQ"],
        "weights": [0.30, 0.30, 0.20, 0.10, 0.10],
        "asset_classes": {
            "SPY": "미국주식",
            "TLT": "장기채권",
            "IEF": "중기채권",
            "GLD": "금",
            "VNQ": "리츠"
        }
    },
    "추천 B_성장형": {
        "tickers": ["QQQ", "SPY", "SMH", "GLD", "VNQ"],
        "weights": [0.35, 0.25, 0.20, 0.10, 0.10],
        "asset_classes": {
            "QQQ": "나스닥",
            "SPY": "미국주식",
            "SMH": "반도체",
            "GLD": "금",
            "VNQ": "리츠"
        }
    }
}

# 최근 5년 백테스트 기간
end_date = datetime.today()
start_date = end_date - timedelta(days=365 * 5)

print("백테스트 시작일:", start_date.date())
print("백테스트 종료일:", end_date.date())

def validate_portfolio(tickers, weights):
    """
    포트폴리오 입력값 검증
    """
    if len(tickers) != len(weights):
        raise ValueError("tickers와 weights의 길이가 다릅니다.")

    if not np.isclose(sum(weights), 1.0):
        raise ValueError(f"weights 합계가 1이 아닙니다. 현재 합계: {sum(weights)}")

    if any(w < 0 for w in weights):
        raise ValueError("weights에는 음수가 들어갈 수 없습니다.")


def download_adjusted_prices(tickers, start_date, end_date):
    """
    yfinance로 수정종가 다운로드.
    yfinance 버전에 따라 Adj Close가 없을 수 있어 auto_adjust=True 기반 Close도 처리.
    """
    data = yf.download(
        tickers,
        start=start_date,
        end=end_date,
        auto_adjust=False,
        progress=False
    )

    if data.empty:
        raise ValueError("가격 데이터를 가져오지 못했습니다. 티커를 확인하세요.")

    # 여러 티커일 때
    if isinstance(data.columns, pd.MultiIndex):
        if "Adj Close" in data.columns.get_level_values(0):
            prices = data["Adj Close"].copy()
        else:
            prices = data["Close"].copy()
    else:
        # 티커가 하나일 때
        if "Adj Close" in data.columns:
            prices = data[["Adj Close"]].copy()
            prices.columns = tickers
        else:
            prices = data[["Close"]].copy()
            prices.columns = tickers

    prices = prices.dropna(how="all")
    prices = prices.ffill().dropna()

    # 혹시 단일 티커 Series가 되면 DataFrame으로 변환
    if isinstance(prices, pd.Series):
        prices = prices.to_frame(name=tickers[0])

    return prices


def calculate_daily_returns(prices):
    """
    일별 수익률 계산
    """
    returns = prices.pct_change().dropna()
    return returns


def calculate_portfolio_returns(asset_returns, weights):
    """
    자산별 일별수익률과 비중을 이용해 포트폴리오 일별수익률 계산
    """
    weights_array = np.array(weights)
    portfolio_returns = asset_returns.dot(weights_array)
    portfolio_returns.name = "portfolio_return"
    return portfolio_returns


def calculate_cumulative_value(portfolio_returns, initial_amount=100):
    """
    누적 포트폴리오 가치 계산
    """
    cumulative_value = initial_amount * (1 + portfolio_returns).cumprod()
    cumulative_value.name = "portfolio_value"
    return cumulative_value


def calculate_mdd(cumulative_value):
    """
    MDD 계산.
    누적가치 기준 최고점 대비 하락률 중 최저값.
    """
    running_max = cumulative_value.cummax()
    drawdown = cumulative_value / running_max - 1
    mdd = drawdown.min()
    return mdd, drawdown


def calculate_sortino_ratio(portfolio_returns, risk_free_rate=0.035):
    """
    소르티노 비율 계산.
    하방 변동성만 위험으로 반영.
    """
    annual_return = portfolio_returns.mean() * TRADING_DAYS
    daily_risk_free = risk_free_rate / TRADING_DAYS

    downside_returns = portfolio_returns[portfolio_returns < daily_risk_free] - daily_risk_free
    downside_deviation = np.sqrt((downside_returns ** 2).mean()) * np.sqrt(TRADING_DAYS)

    if downside_deviation == 0 or np.isnan(downside_deviation):
        return np.nan

    sortino = (annual_return - risk_free_rate) / downside_deviation
    return sortino


def calculate_after_tax_return(nominal_return, tax_config):
    """
    단순 세후수익률 계산.

    현재 버전은 MVP용 단순 계산:
    세후수익률 = 명목수익률 - 세금비용 - 거래수수료 - 환전비용

    실제 세법 전체를 반영한 것이 아니라,
    대시보드 시연용으로 비용 차감 구조를 보여주는 목적.
    """
    dividend_tax_rate = tax_config.get("dividend_tax_rate", 0.154)
    capital_gains_tax_rate = tax_config.get("capital_gains_tax_rate", 0.22)
    trading_fee_rate = tax_config.get("trading_fee_rate", 0.001)
    fx_fee_rate = tax_config.get("fx_fee_rate", 0.002)
    annual_turnover = tax_config.get("annual_turnover", 1.0)

    # 단순 가정: 전체 수익 중 30%는 배당/이자 성격, 70%는 자본차익 성격
    income_return = nominal_return * 0.3
    capital_gain_return = nominal_return * 0.7

    income_tax_cost = max(income_return, 0) * dividend_tax_rate
    capital_gains_tax_cost = max(capital_gain_return, 0) * capital_gains_tax_rate

    trading_cost = trading_fee_rate * annual_turnover
    fx_cost = fx_fee_rate * annual_turnover

    after_tax_return = nominal_return - income_tax_cost - capital_gains_tax_cost - trading_cost - fx_cost

    tax_detail = {
        "nominal_return": nominal_return,
        "income_tax_cost": income_tax_cost,
        "capital_gains_tax_cost": capital_gains_tax_cost,
        "trading_cost": trading_cost,
        "fx_cost": fx_cost,
        "after_tax_return": after_tax_return
    }

    return after_tax_return, tax_detail


def calculate_metrics(portfolio_returns, cumulative_value, risk_free_rate=0.035, tax_config=None):
    """
    6종 지표 계산:
    기대수익률, 변동성, 샤프지수, MDD, 세후수익률, 소르티노 비율
    """
    annual_return = portfolio_returns.mean() * TRADING_DAYS
    annual_volatility = portfolio_returns.std() * np.sqrt(TRADING_DAYS)

    if annual_volatility == 0 or np.isnan(annual_volatility):
        sharpe_ratio = np.nan
    else:
        sharpe_ratio = (annual_return - risk_free_rate) / annual_volatility

    mdd, drawdown = calculate_mdd(cumulative_value)
    sortino_ratio = calculate_sortino_ratio(portfolio_returns, risk_free_rate)

    if tax_config is None:
        after_tax_return = np.nan
        tax_detail = {}
    else:
        after_tax_return, tax_detail = calculate_after_tax_return(annual_return, tax_config)

    metrics = {
        "expected_return": annual_return,
        "volatility": annual_volatility,
        "sharpe_ratio": sharpe_ratio,
        "mdd": mdd,
        "after_tax_return": after_tax_return,
        "sortino_ratio": sortino_ratio
    }

    return metrics, drawdown, tax_detail


def make_allocation_chart_data(tickers, weights, asset_classes=None):
    """
    도넛/파이 차트용 데이터 생성
    """
    chart_data = []
    for ticker, weight in zip(tickers, weights):
        chart_data.append({
            "ticker": ticker,
            "asset_class": asset_classes.get(ticker, "기타") if asset_classes else "기타",
            "weight": weight,
            "weight_percent": weight * 100
        })
    return chart_data


def make_backtest_chart_data(cumulative_value):
    """
    프론트엔드 라인 차트용 데이터 생성
    """
    df = cumulative_value.reset_index()
    df.columns = ["date", "portfolio_value"]
    df["date"] = df["date"].dt.strftime("%Y-%m-%d")
    return df.to_dict(orient="records")


def make_drawdown_chart_data(drawdown):
    """
    MDD/낙폭 차트용 데이터 생성
    """
    df = drawdown.reset_index()
    df.columns = ["date", "drawdown"]
    df["date"] = df["date"].dt.strftime("%Y-%m-%d")
    df["drawdown_percent"] = df["drawdown"] * 100
    return df.to_dict(orient="records")


def make_correlation_heatmap_data(asset_returns):
    """
    상관관계 히트맵용 데이터 생성
    """
    corr = asset_returns.corr()

    heatmap_data = []
    for row_asset in corr.index:
        for col_asset in corr.columns:
            heatmap_data.append({
                "asset_x": row_asset,
                "asset_y": col_asset,
                "correlation": corr.loc[row_asset, col_asset]
            })

    return corr, heatmap_data


def run_single_portfolio_analysis(
    portfolio_name,
    portfolio_config,
    start_date,
    end_date,
    initial_amount=100,
    risk_free_rate=0.035,
    tax_config=None
):
    """
    단일 포트폴리오 전체 분석 실행
    """
    tickers = portfolio_config["tickers"]
    weights = portfolio_config["weights"]
    asset_classes = portfolio_config.get("asset_classes", {})

    validate_portfolio(tickers, weights)

    prices = download_adjusted_prices(tickers, start_date, end_date)
    prices = prices[tickers]  # 입력 순서 유지

    asset_returns = calculate_daily_returns(prices)
    portfolio_returns = calculate_portfolio_returns(asset_returns, weights)
    cumulative_value = calculate_cumulative_value(portfolio_returns, initial_amount)

    metrics, drawdown, tax_detail = calculate_metrics(
        portfolio_returns,
        cumulative_value,
        risk_free_rate=risk_free_rate,
        tax_config=tax_config
    )

    corr_matrix, corr_heatmap_data = make_correlation_heatmap_data(asset_returns)

    result = {
        "portfolio_name": portfolio_name,
        "tickers": tickers,
        "weights": weights,
        "metrics": metrics,
        "tax_detail": tax_detail,
        "allocation_chart": make_allocation_chart_data(tickers, weights, asset_classes),
        "backtest_chart": make_backtest_chart_data(cumulative_value),
        "drawdown_chart": make_drawdown_chart_data(drawdown),
        "correlation_heatmap": corr_heatmap_data,
        "raw": {
            "prices": prices,
            "asset_returns": asset_returns,
            "portfolio_returns": portfolio_returns,
            "cumulative_value": cumulative_value,
            "drawdown": drawdown,
            "correlation_matrix": corr_matrix
        }
    }

    return result

all_results = {}

for name, config in portfolios.items():
    print(f"분석 중: {name}")
    result = run_single_portfolio_analysis(
        portfolio_name=name,
        portfolio_config=config,
        start_date=start_date,
        end_date=end_date,
        initial_amount=initial_amount,
        risk_free_rate=risk_free_rate,
        tax_config=tax_config
    )
    all_results[name] = result

print("분석 완료")

summary_rows = []

for name, result in all_results.items():
    metrics = result["metrics"]
    summary_rows.append({
        "포트폴리오": name,
        "기대수익률": metrics["expected_return"],
        "변동성": metrics["volatility"],
        "샤프지수": metrics["sharpe_ratio"],
        "MDD": metrics["mdd"],
        "세후수익률": metrics["after_tax_return"],
        "소르티노비율": metrics["sortino_ratio"]
    })

summary_df = pd.DataFrame(summary_rows)

# 보기 좋게 % 변환한 표
display_df = summary_df.copy()

for col in ["기대수익률", "변동성", "MDD", "세후수익률"]:
    display_df[col] = display_df[col].apply(lambda x: f"{x:.2%}")

for col in ["샤프지수", "소르티노비율"]:
    display_df[col] = display_df[col].apply(lambda x: f"{x:.3f}" if pd.notnull(x) else "N/A")

display_df

plt.figure(figsize=(12, 6))

for name, result in all_results.items():
    cumulative_value = result["raw"]["cumulative_value"]
    normalized_value = cumulative_value / cumulative_value.iloc[0] * 100
    plt.plot(normalized_value.index, normalized_value.values, label=name)

plt.title("5년 백테스트 누적 수익률 비교")
plt.xlabel("Date")
plt.ylabel("Portfolio Value (Start = 100)")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))

for name, result in all_results.items():
    drawdown = result["raw"]["drawdown"]
    plt.plot(drawdown.index, drawdown.values * 100, label=name)

plt.title("포트폴리오별 Drawdown 비교")
plt.xlabel("Date")
plt.ylabel("Drawdown (%)")
plt.legend()
plt.grid(True)
plt.show()

target_portfolio = "추천 A_안정형"

allocation_data = all_results[target_portfolio]["allocation_chart"]
labels = [item["ticker"] for item in allocation_data]
sizes = [item["weight_percent"] for item in allocation_data]

plt.figure(figsize=(7, 7))
plt.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=90)
plt.title(f"{target_portfolio} 자산배분")
plt.show()

target_portfolio = "추천 A_안정형"

corr_matrix = all_results[target_portfolio]["raw"]["correlation_matrix"]

plt.figure(figsize=(8, 6))
plt.imshow(corr_matrix, aspect="auto")
plt.colorbar(label="Correlation")
plt.xticks(range(len(corr_matrix.columns)), corr_matrix.columns, rotation=45)
plt.yticks(range(len(corr_matrix.index)), corr_matrix.index)
plt.title(f"{target_portfolio} 자산 간 상관관계 히트맵")

for i in range(len(corr_matrix.index)):
    for j in range(len(corr_matrix.columns)):
        plt.text(j, i, f"{corr_matrix.iloc[i, j]:.2f}", ha="center", va="center")

plt.tight_layout()
plt.show()

frontend_json = {}

for name, result in all_results.items():
    frontend_json[name] = {
        "portfolio_name": result["portfolio_name"],
        "metrics": result["metrics"],
        "tax_detail": result["tax_detail"],
        "allocation_chart": result["allocation_chart"],
        "backtest_chart": result["backtest_chart"],
        "drawdown_chart": result["drawdown_chart"],
        "correlation_heatmap": result["correlation_heatmap"]
    }

# JSON 미리보기
print(json.dumps(frontend_json["추천 A_안정형"], ensure_ascii=False, indent=2)[:3000])

with open("portfolio_analysis_result.json", "w", encoding="utf-8") as f:
    json.dump(frontend_json, f, ensure_ascii=False, indent=2)

summary_df.to_csv("portfolio_metrics_summary.csv", index=False, encoding="utf-8-sig")

print("저장 완료:")
print("- portfolio_analysis_result.json")
print("- portfolio_metrics_summary.csv")

stress_scenarios = {
    "미국 기준금리 100bp 인상": {
        "미국주식": -0.06,
        "나스닥": -0.10,
        "반도체": -0.12,
        "장기채권": -0.12,
        "중기채권": -0.05,
        "금": 0.03,
        "리츠": -0.08,
        "원자재": 0.02
    },
    "원달러 환율 급등": {
        "미국주식": 0.05,
        "나스닥": 0.05,
        "반도체": 0.05,
        "장기채권": 0.02,
        "중기채권": 0.01,
        "금": 0.08,
        "리츠": -0.03,
        "원자재": 0.04
    },
    "글로벌 원자재 인플레이션": {
        "미국주식": -0.05,
        "나스닥": -0.08,
        "반도체": -0.08,
        "장기채권": -0.06,
        "중기채권": -0.03,
        "금": 0.07,
        "리츠": -0.04,
        "원자재": 0.12
    }
}


def run_stress_test(portfolio_config, stress_scenarios, initial_amount):
    tickers = portfolio_config["tickers"]
    weights = portfolio_config["weights"]
    asset_classes = portfolio_config.get("asset_classes", {})

    scenario_results = []

    for scenario_name, shock_map in stress_scenarios.items():
        portfolio_shock = 0

        asset_impacts = []
        for ticker, weight in zip(tickers, weights):
            asset_class = asset_classes.get(ticker, "기타")
            shock = shock_map.get(asset_class, 0)
            weighted_impact = weight * shock
            portfolio_shock += weighted_impact

            asset_impacts.append({
                "ticker": ticker,
                "asset_class": asset_class,
                "weight": weight,
                "shock": shock,
                "weighted_impact": weighted_impact
            })

        scenario_results.append({
            "scenario": scenario_name,
            "portfolio_return_impact": portfolio_shock,
            "estimated_pnl": initial_amount * portfolio_shock,
            "estimated_value_after_shock": initial_amount * (1 + portfolio_shock),
            "asset_impacts": asset_impacts
        })

    return scenario_results


stress_results = {}

for name, config in portfolios.items():
    stress_results[name] = run_stress_test(config, stress_scenarios, initial_amount)

stress_summary_rows = []

for portfolio_name, scenario_list in stress_results.items():
    for item in scenario_list:
        stress_summary_rows.append({
            "포트폴리오": portfolio_name,
            "시나리오": item["scenario"],
            "예상 충격률": item["portfolio_return_impact"],
            "예상 손익": item["estimated_pnl"],
            "충격 후 예상 가치": item["estimated_value_after_shock"]
        })

stress_summary_df = pd.DataFrame(stress_summary_rows)

stress_display_df = stress_summary_df.copy()
stress_display_df["예상 충격률"] = stress_display_df["예상 충격률"].apply(lambda x: f"{x:.2%}")
stress_display_df["예상 손익"] = stress_display_df["예상 손익"].apply(lambda x: f"{x:,.0f}원")
stress_display_df["충격 후 예상 가치"] = stress_display_df["충격 후 예상 가치"].apply(lambda x: f"{x:,.0f}원")

stress_display_df

with open("portfolio_stress_test_result.json", "w", encoding="utf-8") as f:
    json.dump(stress_results, f, ensure_ascii=False, indent=2)

stress_summary_df.to_csv("portfolio_stress_test_summary.csv", index=False, encoding="utf-8-sig")

print("저장 완료:")
print("- portfolio_stress_test_result.json")
print("- portfolio_stress_test_summary.csv")