# ruff: noqa: E501, F401
"""portfolio_logic.py — re-export 파사드.

모든 로직은 서브모듈로 분할됨.
외부 importer(테스트·tax_advice 등) 호환을 위해 여기서 re-export 한다.

    모듈 구조:
    constants.py      — §0 기본설정 + §2 기준표
    assets.py          — §1 자산군 정의
    models.py          — §3 요청/응답 Pydantic 모델
    utils.py           — §4 기본 유틸
    prices.py          — §5 가격 데이터 (yfinance)
    expected_returns.py — §6 기대수익률
    tax_accounts.py    — §7 세금/계좌
    metrics.py         — §8-9 지표 계산·기준표 평가
    generation.py      — §10 생성/점수화
    responses.py       — §11 응답 생성
    analysis.py        — §12 전체 분석 실행
    adapters.py        — §12-1 입력 어댑터
    formatters.py      — §12-2 응답 포맷터
    router.py          — §13-14 API 엔드포인트
"""

from .constants import (
    TRADING_DAYS,
    SORTINO_NO_DOWNSIDE_CAP,
    MIN_COMMON_PRICE_OBSERVATIONS,
    MAX_SESSION_REQUEST_STORE_SIZE,
    BACKTEST_BASE_INDEX,
    SEPARATE_TAX_BOND_MIN_HOLDING_YEARS,
    VOL_STRESS_BETA,
    VOL_STRESS_CAP,
    DEFAULT_RANDOM_SEED,
    MONTE_CARLO_METRIC_RANGE_VERSION,
    MONTE_CARLO_METRIC_RANGE_SIMULATIONS,
    MONTE_CARLO_METRIC_RANGE_MAX_HORIZON_YEARS,
    MONTE_CARLO_METRIC_RANGE_STEPS_PER_YEAR,
    MONTE_CARLO_METRIC_RANGE_SEED_OFFSET,
    MONTE_CARLO_METRIC_RANGE_PERCENTILES,
    MONTE_CARLO_METRIC_RANGE_DISPLAY_LOWER,
    MONTE_CARLO_METRIC_RANGE_DISPLAY_CENTER,
    MONTE_CARLO_METRIC_RANGE_DISPLAY_UPPER,
    MIN_BETA_OBSERVATIONS,
    PORTFOLIO_B_MIN_WEIGHT_DISTANCE,
    PRICE_SNAPSHOT_VERSION,
    PRICE_SNAPSHOT_DIR,
    PRICE_SNAPSHOT_PATH,
    _PRICE_SNAPSHOT_LOCK,
    BenchmarkKey,
    DEFAULT_BENCHMARK_KEY,
    BENCHMARK_POLICY_VERSION,
    BENCHMARK_CONFIGS,
    BENCHMARK_SERIES_KEYS,
    PENSION_RECEIVE_AGE,
    DEFAULT_RISK_FREE_RATE,
    DEFAULT_CASH_RETURN,
    FINANCIAL_INCOME_COMPREHENSIVE_TAX_THRESHOLD,
    OVERSEAS_STOCK_GAIN_DEDUCTION,
    OVERSEAS_STOCK_CAPITAL_GAINS_TAX_RATE,
    DEFAULT_WITHHOLDING_TAX_RATE,
    ISA_GENERAL_TAX_FREE_LIMIT,
    ISA_SEOGMIN_TAX_FREE_LIMIT,
    ISA_LOW_TAX_RATE,
    ISA_MANDATORY_HOLDING_YEARS,
    ISA_ANNUAL_CONTRIBUTION_LIMIT,
    ISA_TOTAL_CONTRIBUTION_LIMIT,
    IRP_PENSION_COMBINED_TAX_CREDIT_LIMIT,
    IRP_TAX_CREDIT_RATE_HIGH_INCOME,
    IRP_TAX_CREDIT_RATE_LOW_INCOME,
    TAX_RULE_TABLE_VERSION,
    TAX_RULE_EFFECTIVE_DATE,
    TAX_RULE_TABLE,
    SECOND_PORTFOLIO_MAX_CORRELATION,
    GUIDELINE_RULES,
    SELECTION_RISK_CONTROLS,
    SELECTION_RANKING_BASIS,
)
from .assets import (
    ASSET_TICKERS,
    ASSET_NAMES_KR,
    LEGACY_ASSET_ALIASES,
    UNIQUE_ASSETS,
    STOCK_ASSETS,
    OVERSEAS_STOCK_CAPITAL_GAIN_ASSETS,
    OVERSEAS_STOCK_ASSETS,
    BOND_ASSETS,
    BOND_CASH_ASSETS,
    ALTERNATIVE_ASSETS,
    CASH_LIKE_ASSETS,
    INCOME_TAXABLE_ASSETS,
    ASSET_INCOME_YIELD_ASSUMPTIONS,
    ISA_PRIORITY_ASSETS,
    IRP_PRIORITY_ASSETS,
    ASSET_DURATION_YEARS,
    INTEREST_RATE_SENSITIVE_ASSETS,
    FX_SENSITIVE_ASSETS,
    CLIENT_RISK_LEVEL,
    RISK_LEVEL_NAME,
)
from .models import (
    IPSRequest,
    ScenarioRequest,
    PortfolioCalculateResponse,
    PortfolioStressTestResponse,
    AnalysisRequest,
    PortfolioRequest,
)
from .utils import (
    SESSION_REQUEST_STORE,
    model_to_dict,
    canonicalize_asset_key,
    canonicalize_weights,
    canonicalize_asset_return_map,
    validate_unique_asset,
    validate_weights,
    validate_required_assets_available,
    normalize_weights,
    get_default_current_weights,
    cap01,
    safe_float,
    safe_round,
    normalize_target_after_tax_return,
    get_benchmark_config,
    get_benchmark_catalog,
    attach_benchmark_returns,
    save_session_request,
    public_http_exception,
    convert_analysis_to_portfolio_request,
)
from .prices import (
    _empty_benchmark_snapshot,
    download_benchmark_returns,
    _price_snapshot_key,
    _read_price_snapshot_store,
    _frame_to_snapshot_payload,
    _snapshot_payload_to_frame,
    _save_price_frame_snapshot,
    _load_price_frame_snapshot,
    _apply_live_data_metadata,
    _apply_cached_data_metadata,
    _download_price_data_live,
    download_price_data,
    _download_backtest_price_data_live,
    download_backtest_price_data,
    calculate_daily_returns,
)
from .expected_returns import (
    calculate_expected_returns,
)
from .tax_accounts import (
    get_common_tax_rules,
    estimate_income_profit_for_asset,
    estimate_overseas_capital_gain_profit_for_asset,
    estimate_taxable_financial_income,
    resolve_external_financial_income_krw,
    calculate_financial_income_comprehensive_tax_status,
    estimate_overseas_stock_capital_gains_tax,
    calculate_isa_status,
    calculate_irp_status,
    allocate_account_buckets,
    estimate_tax_saving_effect,
    calculate_six_strategy_tax_model,
    calculate_after_tax_return,
)
from .metrics import (
    calculate_mdd,
    build_portfolio_benchmark,
    align_portfolio_and_benchmark_returns,
    calculate_benchmark_comparisons,
    calculate_beta,
    calculate_sortino,
    calculate_historical_var,
    calculate_risk_contribution,
    evaluate_selection_risk_controls,
    calculate_asset_group_weights,
    calculate_portfolio_duration,
    target_duration_by_horizon,
    calculate_duration_fit_score,
    calculate_isa_locked_amount,
    calculate_liquidity_coverage,
    calculate_stress_test,
    _vol_multiplier,
    derive_asset_shocks_from_macro,
    CRISIS_SCENARIO_SHOCKS,
    resolve_scenario_shocks,
    apply_return_shocks,
    shift_expected_returns,
    _nearest_positive_semidefinite,
    _metric_percentile_payload,
    _effective_tax_rate_from_breakdown,
    calculate_monte_carlo_metric_ranges,
    calculate_metric_amounts,
    calculate_metrics,
    calculate_cumulative_returns,
    calculate_benchmark_cumulative_returns,
    calculate_all_benchmark_cumulative_returns,
    evaluate_guideline_detail,
    check_guideline,
    classify_portfolio_by_guidelines,
    is_suitable_for_client,
)
from .generation import (
    is_separate_tax_bond_allowed,
    get_effective_unique_asset,
    get_recommendation_eligible_assets,
    build_constraint_warnings,
    generate_random_weights,
    apply_unique_constraint,
    build_selection_rank_tuple,
    build_portfolio_b_rank_tuple,
    build_portfolio_b_fallback_rank_tuple,
    build_selection_summary,
    calculate_portfolio_return_series,
    calculate_portfolio_return_correlation,
    calculate_weight_distance,
    find_recommended_portfolios,
)
from .responses import (
    build_guideline_report,
    build_portfolio_response,
    build_asset_summary,
    get_guideline_definition,
    extract_backtest_payload,
    build_isa_tax_card,
    build_irp_tax_card,
    build_taxable_account_card,
    TAX_STRATEGY_META,
    build_tax_strategy_reason,
    build_six_tax_strategy_cards,
    build_tax_optimizer_payload,
    build_tax_optimizer_map,
    extract_tax_inputs_payload,
)
from .analysis import (
    run_analysis_core,
    run_full_analysis,
)
from .adapters import (
    KOREAN_MONEY_UNITS,
    parse_amount_krw,
    stringify_unique_value,
    find_keyword_window,
    truncate_at_stop_keywords,
    find_account_segment,
    parse_start_year_from_text,
    calculate_account_age_years_from_start_year,
    parse_relative_years_from_text,
    parse_amount_near_keywords,
    parse_explicit_money_amount_krw,
    parse_current_year_contribution,
    contains_negative_account_signal,
    parse_liquidity_need_amount,
    extract_generic_client_context,
    extract_unique_profile,
    apply_unique_profile_to_ips_payload,
    normalize_risk_profile_value,
    normalize_liquidity_value,
    normalize_tax_sensitivity_value,
    normalize_unique_asset_value,
    extract_flat_ips_payload,
    extract_request_metadata,
    extract_current_weights_from_portfolio,
    extract_optional_age,
    normalize_analysis_request_payload,
)
from .formatters import (
    rate_to_percent,
    build_allocation_payload,
    build_backtest_payload,
    build_metrics_payload,
    build_metrics_krw_payload,
    build_tax_summary,
    build_tax_payload,
    build_spec_portfolio_item,
    build_portfolio_calculate_response,
)
from .router import (
    router,
    StressMetricsRequest,
)
